
export const translateNormalizeQuery = (splittedQuery: string[]) => {
  const normalizationMap: Record<string, string> = {
    'апл': 'apple',
    'епл': 'apple',
    'телефон': 'iphone',
    'мобілка': 'iphone',
    'айфон': 'iphone',
    'айфони': 'iphone',
    'телефони': 'iphone',
    'мобілки': 'iphone',
    'ейр': 'air',
    'аір': 'air',
    'еір': 'air',
    'айр': 'air',
    'айпад': 'ipad',
    'айпади': 'ipad',
    'ейпед': 'ipad',
    'ейпеди': 'ipad',
    'планшет': 'ipad',
    'планшети': 'ipad',
    'еплвотч': 'watch',
    'еплватч': 'watch',
    'часи': 'watch',
    'годинник': 'watch',
    'годинники': 'watch',
    'аксесуар': 'watch',
    'аксесуари': 'watch',
    'еплвотчі': 'watch',
    'еплватчі': 'watch',
    'аплвотч': 'watch',
    'аплвотчі': 'watch',
    'вотч': 'watch',
    'вотчі': 'watch',
    'про': 'pro',
    'прошка': 'pro',
    'макс': 'max',
    'спейсгрей': 'spacegray',
    'роз': 'rosegold',
    'роуз': 'rosegold',
    'рос': 'rosegold',
    'росголд': 'rosegold',
    'розголд': 'rosegold',
    'роузголд': 'rosegold',
    'міднайтгрін': 'midnightgreen',
    'білі': 'white',
    'білий': 'white',
    'уайт': 'white',
    'вайт': 'white',
    'кораловий': 'coral',
    'корал': 'coral',
    'коралові': 'coral',
    'жовтий': 'yellow',
    'жовті': 'yellow',
    'сіера': 'sierablue',
    'сієра': 'sierablue',
    'сіераблу': 'sierablue',
    'сієраблу': 'sierablue',
    'сіераблю': 'sierablue',
    'світлоголубий': 'sierablue',
    'міднайт': 'midnight',
    'графіт': 'graphite',
    'графітовий': 'graphite',
    'графітові': 'graphite',
    'пінк': 'pink',
    'розовий': 'pink',
    'рожевий': 'pink',
    'розові': 'pink',
    'рожеві': 'pink',
    'блу': 'blu',
    'блю': 'blu',
    'синій': 'blu',
    'сині': 'blu',
    'старлайт': 'starlight',
    'кремовий': 'starlight',
    'кремові': 'starlight',
    'скайблю': 'sky-blue',
    'скайблу': 'sky-blue',
    'голубий': 'sky-blue',
    'голубі': 'sky-blue',
    'спейсблек': 'spaceblack',
    'голд': 'gold',
    'голден': 'gold',
    'золото': 'gold',
    'золотий': 'gold',
    'золоті': 'gold',
    'темносірі': 'spacegray',
    'темносірий': 'spacegray',
    'грей': 'spacegray',
    'срібний': 'silver',
    'срібні': 'silver',
    'сірі': 'silver',
    'світлосірі': 'silver',
    'срібло': 'silver',
    'срібляний': 'silver',
    'сіріий': 'silver',
    'світлосірий': 'silver',
    'грін': 'green',
    'зелений': 'green',
    'зелені': 'green',
    'оливковий': 'green',
    'оливкові': 'green',
    'олива': 'green',
    'чорний': 'black',
    'чорні': 'black',
    'темний': 'black',
    'темні': 'black',
    'фіолетогвий': 'purple',
    'фіолетові': 'purple',
    'ліловий': 'purple',
    'лілові': 'purple',
    'перпл': 'purple',
    'пурпл': 'purple',
    'пьорпл': 'purple',
    'ред': 'red',
    'червоний': 'red',
    'красний': 'red',
  };

  const normalizedQuery = splittedQuery.map(word => {
    const normalizedWord = normalizationMap[word];

    return normalizedWord ? normalizedWord : word;
  });

  return normalizedQuery;
};